server:
  port: 8082

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
      routes[0]:
        id: users-status-check
        uri: lb://users-ws
        predicates[0]: Path=/users/status/check
        predicates[1]: Method=GET
        filters[0]: RemoveRequestHeader=Cookie

#  cloud:
#    gateway:
#      discovery:
#        locator:
#          enabled: true
#          lower-case-service-id: true


eureka:
  client:
    service-url.defaultZone: http://localhost:8010/eureka
  instance:
    prefer-ip-address: true
